"""
HablaRápido - Spanish A2 Speaking Bot
Single-file bot, matches existing VM stack (systemd + venv + .env + google-creds.json)

Word packs loaded from word_packs.json (generated by generate_images.py).
Pre-generated images live in ./images/ — sent instantly, no wait.
Custom packs uploaded via JSON are stored in Google Sheets; their images
are generated on the fly since they're new words.
"""

import os
import json
import logging
import asyncio
import uuid
import base64
import requests
from datetime import datetime
from dotenv import load_dotenv

import aiohttp
from telegram import Update, InlineKeyboardButton, InlineKeyboardMarkup
from telegram.ext import (
    Application, CommandHandler, MessageHandler,
    CallbackQueryHandler, filters, ContextTypes
)
import gspread
from google.oauth2.service_account import Credentials
from google.cloud import texttospeech, speech

load_dotenv()
logging.basicConfig(
    format='%(asctime)s - %(levelname)s - %(message)s',
    level=logging.INFO
)
logger = logging.getLogger(__name__)

# ─── CONFIG ──────────────────────────────────────────────────────────────────

TELEGRAM_TOKEN   = os.getenv("TELEGRAM_TOKEN")
DEEPSEEK_API_KEY = os.getenv("DEEPSEEK_API_KEY")
DEEPSEEK_URL     = "https://api.deepseek.com/v1/chat/completions"
GOOGLE_CREDS     = "google-creds.json"
SHEET_ID         = os.getenv("SHEET_ID")

YANDEX_API_KEY   = os.getenv("YANDEX_API_KEY")
YANDEX_FOLDER_ID = os.getenv("YANDEX_FOLDER_ID")
YANDEX_ART_URL   = "https://llm.api.cloud.yandex.net/foundationModels/v1/imageGenerationAsync"

IMAGES_DIR  = "images"
PACKS_FILE  = "word_packs.json"
TAB_VOCAB   = "Spanish A2"
TAB_PACKS   = "Custom Packs"

# ─── LOAD WORD PACKS ─────────────────────────────────────────────────────────
# word_packs.json is created/updated by generate_images.py
# Falls back to empty dict with a clear error if file is missing.

def load_builtin_packs() -> dict:
    if not os.path.exists(PACKS_FILE):
        logger.error(
            f"{PACKS_FILE} not found. Run generate_images.py first to create it."
        )
        return {}
    with open(PACKS_FILE, "r", encoding="utf-8") as f:
        packs = json.load(f)
    logger.info(f"Loaded {len(packs)} built-in packs from {PACKS_FILE}")
    return packs

builtin_packs = load_builtin_packs()
custom_packs  = {}   # loaded from Google Sheets on startup

def all_packs() -> dict:
    return {**builtin_packs, **custom_packs}

# ─── GOOGLE SHEETS ────────────────────────────────────────────────────────────

def get_sheet_client():
    scopes = ["https://www.googleapis.com/auth/spreadsheets"]
    creds  = Credentials.from_service_account_file(GOOGLE_CREDS, scopes=scopes)
    return gspread.authorize(creds)

def get_or_create_tab(sheet, tab_name: str, headers: list):
    try:
        ws = sheet.worksheet(tab_name)
    except gspread.WorksheetNotFound:
        ws = sheet.add_worksheet(title=tab_name, rows=1000, cols=len(headers))
        ws.append_row(headers)
    return ws

def load_custom_packs_from_sheet() -> dict:
    packs = {}
    try:
        client = get_sheet_client()
        sheet  = client.open_by_key(SHEET_ID)
        ws     = get_or_create_tab(sheet, TAB_PACKS, ["pack_name", "word", "english"])
        for row in ws.get_all_records():
            pack = row.get("pack_name", "").strip()
            word = row.get("word", "").strip()
            eng  = row.get("english", "").strip()
            if pack and word:
                packs.setdefault(pack, []).append({"word": word, "english": eng})
        logger.info(f"Loaded custom packs from sheet: {list(packs.keys())}")
    except Exception as e:
        logger.error(f"Failed to load custom packs: {e}")
    return packs

def save_pack_to_sheet(pack_name: str, words: list):
    client = get_sheet_client()
    sheet  = client.open_by_key(SHEET_ID)
    ws     = get_or_create_tab(sheet, TAB_PACKS, ["pack_name", "word", "english"])
    for w in words:
        ws.append_row([pack_name, w["word"], w.get("english", "")])
    logger.info(f"Saved pack '{pack_name}' ({len(words)} words) to sheet")

def get_student_tab_name(user: object) -> str:
    """Return a clean sheet tab name for a student based on their Telegram identity."""
    if user.username:
        name = user.username          # e.g. john_smith
    elif user.first_name:
        name = user.first_name        # e.g. John
        if user.last_name:
            name += f"_{user.last_name}"
    else:
        name = str(user.id)           # fallback to numeric ID
    # Clean to safe sheet tab name (max 50 chars, no special chars)
    safe = "".join(c for c in name if c.isalnum() or c in "_- ")[:50]
    return safe.strip() or str(user.id)

def save_vocab_word(word: str, english: str, theme: str, example: str, user: object):
    try:
        client   = get_sheet_client()
        sheet    = client.open_by_key(SHEET_ID)
        tab_name = get_student_tab_name(user)
        ws       = get_or_create_tab(
            sheet, tab_name,
            ["Date", "Word", "English", "Theme", "Example", "Status"]
        )
        ws.append_row([
            datetime.now().strftime("%Y-%m-%d"),
            word, english, theme, example, "new"
        ])
        logger.info(f"Saved '{word}' to tab '{tab_name}'")
    except Exception as e:
        logger.error(f"Failed to save vocab word: {e}")

# ─── DEEPSEEK ────────────────────────────────────────────────────────────────

async def deepseek(prompt: str) -> str:
    headers = {
        "Authorization": f"Bearer {DEEPSEEK_API_KEY}",
        "Content-Type": "application/json"
    }
    payload = {
        "model": "deepseek-chat",
        "messages": [
            {"role": "system", "content": "You are a friendly Spanish tutor for A2 learners."},
            {"role": "user",   "content": prompt}
        ],
        "temperature": 0.7
    }
    try:
        async with aiohttp.ClientSession() as s:
            async with s.post(
                DEEPSEEK_URL, headers=headers, json=payload,
                timeout=aiohttp.ClientTimeout(total=30)
            ) as r:
                data = await r.json()
                return data["choices"][0]["message"]["content"].strip()
    except Exception as e:
        logger.error(f"DeepSeek error: {e}")
        return "Lo siento, hay un problema técnico."

# ─── GOOGLE TTS (Chirp) ───────────────────────────────────────────────────────

async def make_tts(text: str) -> str | None:
    try:
        creds    = Credentials.from_service_account_file(GOOGLE_CREDS)
        client   = texttospeech.TextToSpeechClient(credentials=creds)
        response = client.synthesize_speech(
            input=texttospeech.SynthesisInput(text=text),
            voice=texttospeech.VoiceSelectionParams(
                language_code="es-US",
                name="es-US-Chirp3-HD-Aoede"
            ),
            audio_config=texttospeech.AudioConfig(
                audio_encoding=texttospeech.AudioEncoding.OGG_OPUS
            )
        )
        path = f"/tmp/tts_{uuid.uuid4()}.ogg"
        with open(path, "wb") as f:
            f.write(response.audio_content)
        return path
    except Exception as e:
        logger.error(f"TTS error: {e}")
        return None

# ─── GOOGLE STT ───────────────────────────────────────────────────────────────

async def transcribe_voice(path: str) -> str | None:
    try:
        creds  = Credentials.from_service_account_file(GOOGLE_CREDS)
        client = speech.SpeechClient(credentials=creds)
        with open(path, "rb") as f:
            audio_data = f.read()
        response = client.recognize(
            config=speech.RecognitionConfig(
                encoding=speech.RecognitionConfig.AudioEncoding.OGG_OPUS,
                sample_rate_hertz=48000,
                language_code="es-ES",
                alternative_language_codes=["es-US", "es-MX"]
            ),
            audio=speech.RecognitionAudio(content=audio_data)
        )
        if response.results:
            return response.results[0].alternatives[0].transcript
    except Exception as e:
        logger.error(f"STT error: {e}")
    return None

# ─── YANDEX ART (on-the-fly, for custom packs only) ──────────────────────────

async def generate_image_yandex_async(word: str, english: str) -> bytes | None:
    """Async Yandex Art generation — used only for custom pack words."""
    prompt = (
        f"Simple colorful cartoon illustration for Spanish vocabulary learning. "
        f"Word: '{word}' ({english}). "
        f"Clean white background, friendly and educational style."
    )
    headers = {
        "Authorization": f"Api-Key {YANDEX_API_KEY}",
        "Content-Type": "application/json",
    }
    payload = {
        "modelUri": f"art://{YANDEX_FOLDER_ID}/yandex-art/latest",
        "generationOptions": {
            "seed": 42,
            "aspectRatio": {"widthRatio": 1, "heightRatio": 1}
        },
        "messages": [{"text": prompt}]
    }
    try:
        async with aiohttp.ClientSession() as session:
            async with session.post(
                YANDEX_ART_URL, headers=headers, json=payload,
                timeout=aiohttp.ClientTimeout(total=30)
            ) as r:
                data = await r.json()
                operation_id = data.get("id")
            if not operation_id:
                return None

            result_url = f"https://llm.api.cloud.yandex.net:443/operations/{operation_id}"
            for attempt in range(36):   # up to 3 minutes
                await asyncio.sleep(5)
                async with session.get(result_url, headers=headers) as r:
                    data = await r.json()
                if data.get("done"):
                    if "error" in data:
                        logger.error(f"Yandex error: {data['error']}")
                        return None
                    img_b64 = data.get("response", {}).get("image")
                    if img_b64:
                        return base64.b64decode(img_b64)
                    return None
    except Exception as e:
        logger.error(f"Yandex Art async error: {e}")
    return None

# ─── IMAGE SENDING ────────────────────────────────────────────────────────────

async def send_word_image(
    chat_id: int,
    context: ContextTypes.DEFAULT_TYPE,
    word_data: dict
):
    """
    Send image for a word.
    - Built-in words: read from ./images/<filename> (instant)
    - Custom words:   generate on the fly via Yandex Art
    """
    image_file = word_data.get("image")

    if image_file:
        # Pre-generated image — send instantly
        img_path = os.path.join(IMAGES_DIR, image_file)
        if os.path.exists(img_path):
            with open(img_path, "rb") as f:
                await context.bot.send_photo(chat_id=chat_id, photo=f)
            return
        else:
            logger.warning(f"Image file not found: {img_path} — falling back to generation")

    # No pre-generated image — generate on the fly (custom pack words)
    word    = word_data["word"]
    english = word_data.get("english", "")
    logger.info(f"Generating image on the fly for custom word: '{word}'")
    img_bytes = await generate_image_yandex_async(word, english)
    if img_bytes:
        await context.bot.send_photo(chat_id=chat_id, photo=img_bytes)

# ─── SESSION HELPERS ──────────────────────────────────────────────────────────

sessions = {}

def get_session(user_id: int) -> dict:
    if user_id not in sessions:
        sessions[user_id] = {
            "theme": None, "words": [], "index": 0,
            "current_word": None, "current_english": None,
            "current_question": None, "help_level": 0,
        }
    return sessions[user_id]

def next_theme(user_id: int) -> str:
    themes  = list(all_packs().keys())
    current = get_session(user_id).get("theme")
    try:
        idx = (themes.index(current) + 1) % len(themes)
    except ValueError:
        idx = 0
    return themes[idx]

# ─── CORE LEARNING FLOW ───────────────────────────────────────────────────────

async def send_word(chat_id: int, context: ContextTypes.DEFAULT_TYPE, s: dict):
    word_data = s["words"][s["index"]]
    word      = word_data["word"]
    english   = word_data.get("english", "")
    s["current_word"]    = word
    s["current_english"] = english
    s["help_level"]      = 0

    # 1. Explanation from DeepSeek
    explanation = await deepseek(
        f"Explain the Spanish word/phrase '{word}' (English: {english}) to an A2 learner. "
        f"Use simple Spanish. One-line definition + one short example sentence. Max 60 words."
    )
    await context.bot.send_message(
        chat_id=chat_id,
        text=f"📚 *{word}* — _{english}_\n\n{explanation}",
        parse_mode="Markdown"
    )

    # 2. Image — fire and forget so it doesn't block the question
    asyncio.create_task(send_word_image(chat_id, context, word_data))

    # 3. Conversation question
    question = await deepseek(
        f"Write ONE short A2-level Spanish conversation question about '{word}'. "
        f"Personal, easy to answer in 1-2 sentences. Question only, no extra text."
    )
    s["current_question"] = question

    # 4. TTS for question
    audio_path = await make_tts(question)

    kb = [
        [InlineKeyboardButton("🆘 I don't understand", callback_data="help"),
         InlineKeyboardButton("🔊 Repeat", callback_data="repeat")],
        [InlineKeyboardButton("⏭ Skip word", callback_data="skip")]
    ]
    markup = InlineKeyboardMarkup(kb)

    if audio_path:
        with open(audio_path, "rb") as f:
            await context.bot.send_voice(
                chat_id=chat_id, voice=f,
                caption=f"🎤 {question}\n\nSend a voice message with your answer",
                parse_mode="Markdown", reply_markup=markup
            )
        os.remove(audio_path)
    else:
        await context.bot.send_message(
            chat_id=chat_id,
            text=f"🎤 {question}\n\nSend a voice message with your answer",
            parse_mode="Markdown", reply_markup=markup
        )

# ─── HANDLERS ─────────────────────────────────────────────────────────────────

async def cmd_start(update: Update, context: ContextTypes.DEFAULT_TYPE):
    packs     = all_packs()
    pack_list = "\n".join(f"  • {k} ({len(v)} words)" for k, v in packs.items())
    await update.message.reply_text(
        "Hi! I'm HablaRápido 🇪🇸\n\n"
        "I help you practice Spanish A2 vocabulary through speaking.\n\n"
        "Commands:\n"
        "/nuevas — start next topic\n"
        "/temas — see all available topics\n"
        "/tema comida — choose a specific topic\n\n"
        "Available topics:\n"
        f"{pack_list}\n\n"
        "To add a custom word pack, send me a .json file.",
        parse_mode=None
    )

async def cmd_temas(update: Update, context: ContextTypes.DEFAULT_TYPE):
    packs   = all_packs()
    builtin = [k for k in packs if k in builtin_packs]
    custom  = [k for k in packs if k not in builtin_packs]
    msg = "Available topics:\n\n"
    msg += "Built-in:\n" + "\n".join(
        f"  • {k} ({len(packs[k])} palabras)" for k in builtin
    )
    if custom:
        msg += "\n\nCustom (Google Sheets):\n" + "\n".join(
            f"  • {k} ({len(packs[k])} palabras)" for k in custom
        )
    msg += "\n\nUse /tema [name] to choose one."
    await update.message.reply_text(msg, parse_mode="Markdown")

async def cmd_tema(update: Update, context: ContextTypes.DEFAULT_TYPE):
    if not context.args:
        await update.message.reply_text("Write the topic name: /tema comida")
        return
    theme = context.args[0].lower().strip()
    if theme not in all_packs():
        await update.message.reply_text(
            f"Topic '{theme}' not found.\nUse /temas to see available topics."
        )
        return
    await start_theme(update, context, theme)

async def cmd_nuevas(update: Update, context: ContextTypes.DEFAULT_TYPE):
    await start_theme(update, context, next_theme(update.effective_user.id))

async def start_theme(update: Update, context: ContextTypes.DEFAULT_TYPE, theme: str):
    user_id = update.effective_user.id
    s       = get_session(user_id)
    s["theme"]            = theme
    s["words"]            = all_packs()[theme]
    s["index"]            = 0
    s["current_question"] = None
    await update.message.reply_text(
        f"🗂 Topic: {theme.replace('_', ' ').capitalize()}  —  {len(s['words'])} words. Let's go! 💪",
        parse_mode=None
    )
    await send_word(update.effective_chat.id, context, s)

async def handle_document(update: Update, context: ContextTypes.DEFAULT_TYPE):
    """Handle .json file upload to add a custom word pack."""
    doc = update.message.document
    if not doc.file_name.endswith(".json"):
        await update.message.reply_text("Please send a .json file")
        return

    await update.message.reply_text("⏳ Processing your pack...")

    file     = await doc.get_file()
    tmp_path = f"/tmp/pack_{uuid.uuid4()}.json"
    await file.download_to_drive(tmp_path)

    try:
        with open(tmp_path, "r", encoding="utf-8") as f:
            data = json.load(f)
        os.remove(tmp_path)
    except Exception as e:
        await update.message.reply_text(f"❌ Error leyendo el JSON: {e}")
        return

    if not isinstance(data, dict):
        await update.message.reply_text(
            "❌ Formato incorrecto. El JSON debe ser:\n"
            '{\n  "nombre_pack": [\n    {"word": "...", "english": "..."}\n  ]\n}'
        )
        return

    saved  = []
    errors = []

    for pack_name, words in data.items():
        if not isinstance(words, list):
            errors.append(f"'{pack_name}' — must be a list")
            continue
        valid = [w for w in words if isinstance(w, dict) and "word" in w]
        if not valid:
            errors.append(f"'{pack_name}' — no valid words found")
            continue
        try:
            save_pack_to_sheet(pack_name, valid)
            custom_packs[pack_name] = valid
            saved.append(f"'{pack_name}' ({len(valid)} words)")
        except Exception as e:
            errors.append(f"'{pack_name}' — error guardando: {e}")

    msg = ""
    if saved:
        msg += "✅ Packs saved to Google Sheets:\n" + "\n".join(f"  • {s}" for s in saved)
        msg += "\n\nImages will be generated on the fly for these packs."
    if errors:
        msg += "\n\n⚠️ *Errores:*\n" + "\n".join(f"  • {e}" for e in errors)
    if not saved and not errors:
        msg = "❌ No valid packs found."
    msg += "\n\nUse /temas to see all topics."
    await update.message.reply_text(msg, parse_mode="Markdown")

async def handle_voice(update: Update, context: ContextTypes.DEFAULT_TYPE):
    user_id = update.effective_user.id
    s       = get_session(user_id)

    if not s.get("current_question"):
        await update.message.reply_text("Use /nuevas to start a session.")
        return

    await context.bot.send_chat_action(chat_id=update.effective_chat.id, action="typing")

    voice_file = await update.effective_message.voice.get_file()
    voice_path = f"/tmp/voice_{uuid.uuid4()}.ogg"
    await voice_file.download_to_drive(voice_path)
    user_text  = await transcribe_voice(voice_path)
    os.remove(voice_path)

    if not user_text:
        await update.message.reply_text("Could not understand the audio. Please try again! 🎤")
        return

    feedback = await deepseek(
        f"You are an encouraging A2 Spanish tutor.\n"
        f"Question asked: {s['current_question']}\n"
        f"Student said: {user_text}\n\n"
        f"Reply in Spanish. Max 3 sentences:\n"
        f"1. Short encouraging comment\n"
        f"2. Correct their sentence naturally if needed\n"
        f"3. Give the corrected/model version prefixed with ✅"
    )

    corrected = None
    for line in feedback.split("\n"):
        if "✅" in line:
            corrected = line.replace("✅", "").strip()
            break
    audio_path = await make_tts(corrected or s["current_question"])

    kb = [
        [InlineKeyboardButton("✅ Save this word", callback_data="save"),
         InlineKeyboardButton("⏭ Next", callback_data="next")]
    ]
    markup = InlineKeyboardMarkup(kb)

    if audio_path:
        with open(audio_path, "rb") as f:
            await context.bot.send_voice(
                chat_id=update.effective_chat.id, voice=f,
                caption=f"_{user_text}_\n\n{feedback}",
                parse_mode="Markdown", reply_markup=markup
            )
        os.remove(audio_path)
    else:
        await update.message.reply_text(
            f"_{user_text}_\n\n{feedback}",
            parse_mode="Markdown", reply_markup=markup
        )

async def handle_callback(update: Update, context: ContextTypes.DEFAULT_TYPE):
    query   = update.callback_query
    await query.answer()
    user_id = update.effective_user.id
    s       = get_session(user_id)
    chat_id = update.effective_chat.id

    if query.data == "save":
        save_vocab_word(
            word=s["current_word"], english=s["current_english"],
            theme=s["theme"],       example=s["current_question"]
        )
        try:
            await query.edit_message_caption(
                caption=f"✅ {s['current_word']} saved to your list!",
                parse_mode="Markdown"
            )
        except Exception:
            await context.bot.send_message(
                chat_id=chat_id,
                text=f"✅ {s['current_word']} saved to your list!",
                parse_mode="Markdown"
            )
        await advance_to_next(chat_id, context, s)

    elif query.data in ("next", "skip"):
        await advance_to_next(chat_id, context, s)

    elif query.data == "repeat":
        if s.get("current_question"):
            audio_path = await make_tts(s["current_question"])
            if audio_path:
                with open(audio_path, "rb") as f:
                    await context.bot.send_voice(chat_id=chat_id, voice=f)
                os.remove(audio_path)

    elif query.data == "help":
        s["help_level"] = s.get("help_level", 0) + 1
        await send_help(chat_id, context, s)

async def send_help(chat_id: int, context: ContextTypes.DEFAULT_TYPE, s: dict):
    level = s["help_level"]
    q     = s["current_question"]

    if level == 1:
        simplified = await deepseek(
            f"Simplify this A2 Spanish question into shorter, easier words. "
            f"Add a vocabulary hint in brackets. Question: '{q}'. One sentence only."
        )
        text = f"🆘 Simpler version:\n\n{simplified}"
    elif level == 2:
        translated = await deepseek(
            f"Translate this Spanish question to English, then give a simple model answer in Spanish.\n"
            f"Question: '{q}'\nFormat:\nEN: [translation]\nModelo: [simple Spanish answer]"
        )
        text = f"🇬🇧 Translation + Model answer:\n\n{translated}"
    else:
        model = await deepseek(
            f"Give a very simple 1-sentence model answer to this question for an A2 learner: '{q}'. "
            f"Spanish only."
        )
        text = f"💡 Full example:\n\n{model}\n\nTry repeating this sentence 🎤"

    kb = [
        [InlineKeyboardButton("🔊 Listen again", callback_data="repeat"),
         InlineKeyboardButton("🆘 More help", callback_data="help")],
        [InlineKeyboardButton("⏭ Skip word", callback_data="skip")]
    ]
    await context.bot.send_message(
        chat_id=chat_id, text=text,
        parse_mode=None,
        reply_markup=InlineKeyboardMarkup(kb)
    )

async def advance_to_next(chat_id: int, context: ContextTypes.DEFAULT_TYPE, s: dict):
    s["index"] += 1
    if s["index"] < len(s["words"]):
        await context.bot.send_message(
            chat_id=chat_id,
            text=f"Word {s['index'] + 1} of {len(s['words'])}..."
        )
        await send_word(chat_id, context, s)
    else:
        await context.bot.send_message(
            chat_id=chat_id,
            text=(
                "🎉 Session complete! Well done!\n\nUse /nuevas for the next topic\nor /temas to choose one."
            ),
            parse_mode=None
        )
        s["current_question"] = None

# ─── STARTUP ──────────────────────────────────────────────────────────────────

async def on_startup(app):
    global custom_packs
    logger.info("Loading custom packs from Google Sheets...")
    custom_packs = load_custom_packs_from_sheet()
    logger.info(f"Ready. All packs: {list(all_packs().keys())}")

# ─── MAIN ────────────────────────────────────────────────────────────────────

def main():
    app = Application.builder().token(TELEGRAM_TOKEN).post_init(on_startup).build()

    app.add_handler(CommandHandler("start",  cmd_start))
    app.add_handler(CommandHandler("help",   cmd_start))
    app.add_handler(CommandHandler("nuevas", cmd_nuevas))
    app.add_handler(CommandHandler("temas",  cmd_temas))
    app.add_handler(CommandHandler("tema",   cmd_tema))
    app.add_handler(MessageHandler(filters.Document.MimeType("application/json"), handle_document))
    app.add_handler(MessageHandler(filters.VOICE, handle_voice))
    app.add_handler(CallbackQueryHandler(handle_callback))

    logger.info("HablaRápido bot starting...")
    app.run_polling(allowed_updates=["message", "callback_query"])

if __name__ == "__main__":
    main()
